package intent

import (
	"fmt"
	"strings"
	"time"

	"github.com/phuc-nt/dandori-cli/internal/db"
	"github.com/phuc-nt/dandori-cli/internal/quality"
)

// ReportData aggregates all data needed for a single-run incident report.
type ReportData struct {
	Run       *db.RunRecord
	Intent    *db.RunIntentEvents
	Quality   *quality.Metrics
	Tools     []db.ToolUsageSummary
	Reasoning []string
}

// TaskReportData aggregates data for a --task (multi-run) incident report.
type TaskReportData struct {
	JiraKey string
	Runs    []*ReportData
}

// BuildRunReport formats a single-run markdown incident report.
func BuildRunReport(d *ReportData) string {
	var sb strings.Builder
	generatedAt := time.Now().UTC().Format(time.RFC3339)

	writeRunHeader(&sb, d.Run)
	writeIntentSection(&sb, d.Intent)
	writeDiffSection(&sb, d.Run, d.Quality)
	writeDecisionsSection(&sb, d.Intent)
	writeToolUsageSection(&sb, d.Tools)
	writeQualitySection(&sb, d.Quality)
	writeReasoningSection(&sb, d.Reasoning)

	fmt.Fprintf(&sb, "\n---\n*Generated by dandori incident-report at %s*\n", generatedAt)
	return sb.String()
}

// BuildTaskReport formats a multi-run markdown incident report for a Jira task.
func BuildTaskReport(d *TaskReportData) string {
	var sb strings.Builder
	generatedAt := time.Now().UTC().Format(time.RFC3339)

	// Cross-run summary
	var totalCost float64
	var totalTokens int
	for _, r := range d.Runs {
		totalCost += r.Run.CostUSD
		totalTokens += r.Run.InputTokens + r.Run.OutputTokens
	}

	fmt.Fprintf(&sb, "# Incident Report — Task %s\n\n", d.JiraKey)
	fmt.Fprintf(&sb, "## Cross-run Summary\n\n")
	fmt.Fprintf(&sb, "| Metric | Value |\n")
	fmt.Fprintf(&sb, "|--------|-------|\n")
	fmt.Fprintf(&sb, "| Total runs | %d |\n", len(d.Runs))
	fmt.Fprintf(&sb, "| Cumulative cost | $%.4f |\n", totalCost)
	fmt.Fprintf(&sb, "| Total tokens | %s |\n", formatTokens(totalTokens))
	fmt.Fprintf(&sb, "| Iteration count | %d |\n\n", len(d.Runs))

	// Per-run blocks
	for i, r := range d.Runs {
		fmt.Fprintf(&sb, "---\n\n## Run %d of %d\n\n", i+1, len(d.Runs))
		writeRunHeader(&sb, r.Run)
		writeIntentSection(&sb, r.Intent)
		writeDiffSection(&sb, r.Run, r.Quality)
		writeDecisionsSection(&sb, r.Intent)
		writeToolUsageSection(&sb, r.Tools)
		writeQualitySection(&sb, r.Quality)
	}

	fmt.Fprintf(&sb, "\n---\n*Generated by dandori incident-report at %s*\n", generatedAt)
	return sb.String()
}

// --- section writers ---

func writeRunHeader(sb *strings.Builder, r *db.RunRecord) {
	runLabel := r.ID
	if len(runLabel) > 8 {
		runLabel = runLabel[:8]
	}

	fmt.Fprintf(sb, "# Incident Report — %s\n\n", r.ID)

	task := r.JiraIssueKey
	if task == "" {
		task = "(none)"
	}
	fmt.Fprintf(sb, "**Task:** %s\n", task)

	agent := r.AgentName
	if agent == "" {
		agent = "(unknown)"
	}
	modelStr := ""
	if r.Model != "" {
		modelStr = fmt.Sprintf(" (%s)", r.Model)
	}
	fmt.Fprintf(sb, "**Agent:** %s%s\n", agent, modelStr)

	startedStr := r.StartedAt.UTC().Format(time.RFC3339)
	if r.StartedAt.IsZero() {
		startedStr = "(unknown)"
	}
	fmt.Fprintf(sb, "**Started:** %s\n", startedStr)

	if r.DurationSec > 0 {
		fmt.Fprintf(sb, "**Duration:** %.0fs\n", r.DurationSec)
	} else {
		fmt.Fprintf(sb, "**Duration:** —\n")
	}

	fmt.Fprintf(sb, "**Status:** %s\n", r.Status)
	fmt.Fprintf(sb, "**Exit code:** %d\n", r.ExitCode)

	tokens := r.InputTokens + r.OutputTokens
	fmt.Fprintf(sb, "**Cost:** $%.4f · %s tokens\n\n", r.CostUSD, formatTokens(tokens))

	_ = runLabel
}

func writeIntentSection(sb *strings.Builder, ie *db.RunIntentEvents) {
	fmt.Fprintf(sb, "## Intent\n\n")

	if ie == nil || ie.Intent == nil {
		fmt.Fprintf(sb, "_no intent captured_\n\n")
		return
	}

	i := ie.Intent

	if i.FirstUserMsg != "" {
		fmt.Fprintf(sb, "> **First message:**\n")
		for _, line := range strings.Split(i.FirstUserMsg, "\n") {
			fmt.Fprintf(sb, "> %s\n", line)
		}
		sb.WriteString("\n")
	}

	if i.Summary != "" {
		fmt.Fprintf(sb, "**Agent summary:** %s\n\n", i.Summary)
	}

	// Spec sources subsection
	fmt.Fprintf(sb, "**Spec sources:**\n\n")
	hasSources := false
	if i.SpecLinks.JiraKey != "" {
		fmt.Fprintf(sb, "- Jira: %s\n", i.SpecLinks.JiraKey)
		hasSources = true
	}
	for _, u := range i.SpecLinks.ConfluenceURLs {
		fmt.Fprintf(sb, "- [Confluence](%s)\n", u)
		hasSources = true
	}
	for _, p := range i.SpecLinks.SourcePaths {
		fmt.Fprintf(sb, "- Local: `%s`\n", p)
		hasSources = true
	}
	if !hasSources {
		fmt.Fprintf(sb, "- _no spec sources recorded_\n")
	}
	sb.WriteString("\n")
}

func writeDiffSection(sb *strings.Builder, r *db.RunRecord, q *quality.Metrics) {
	fmt.Fprintf(sb, "## Diff Stats\n\n")

	hasGit := r.GitHeadBefore != "" || r.GitHeadAfter != ""
	hasMetrics := q != nil && (q.FilesChanged > 0 || q.LinesAdded > 0 || q.LinesRemoved > 0)

	if !hasGit && !hasMetrics {
		fmt.Fprintf(sb, "_no diff data captured_\n\n")
		return
	}

	if hasMetrics {
		fmt.Fprintf(sb, "- Files changed: %d\n", q.FilesChanged)
		fmt.Fprintf(sb, "- Insertions: %d\n", q.LinesAdded)
		fmt.Fprintf(sb, "- Deletions: %d\n", q.LinesRemoved)
	}
	if r.GitHeadBefore != "" {
		fmt.Fprintf(sb, "- HEAD before: `%s`\n", r.GitHeadBefore)
	}
	if r.GitHeadAfter != "" {
		fmt.Fprintf(sb, "- HEAD after:  `%s`\n", r.GitHeadAfter)
	}
	sb.WriteString("\n")
}

func writeDecisionsSection(sb *strings.Builder, ie *db.RunIntentEvents) {
	fmt.Fprintf(sb, "## Key Decisions\n\n")
	fmt.Fprintf(sb, "> ⚠️ Decisions extracted via heuristic — verify against agent transcript before drawing conclusions.\n\n")

	if ie == nil || len(ie.Decisions) == 0 {
		fmt.Fprintf(sb, "_no decisions captured_\n\n")
		return
	}

	for i, d := range ie.Decisions {
		fmt.Fprintf(sb, "### %d. Decision\n\n", i+1)
		fmt.Fprintf(sb, "- **Chose:** %s\n", d.Chosen)
		if len(d.Rejected) > 0 {
			fmt.Fprintf(sb, "- **Rejected:** %s\n", strings.Join(d.Rejected, ", "))
		}
		if d.Rationale != "" {
			fmt.Fprintf(sb, "- **Rationale:** %s\n", d.Rationale)
		}
		sb.WriteString("\n")
	}
}

func writeToolUsageSection(sb *strings.Builder, tools []db.ToolUsageSummary) {
	fmt.Fprintf(sb, "## Tool / Skill Usage (top 5)\n\n")

	if len(tools) == 0 {
		fmt.Fprintf(sb, "_no tool events captured_\n\n")
		return
	}

	fmt.Fprintf(sb, "| Tool | Uses |\n")
	fmt.Fprintf(sb, "|------|------|\n")
	for _, t := range tools {
		fmt.Fprintf(sb, "| %s | %d |\n", t.Tool, t.Count)
	}
	sb.WriteString("\n")
}

func writeQualitySection(sb *strings.Builder, q *quality.Metrics) {
	fmt.Fprintf(sb, "## Quality\n\n")

	if q == nil {
		fmt.Fprintf(sb, "_no quality metrics captured_\n\n")
		return
	}

	lintDeltaStr := fmt.Sprintf("%+d", q.LintDelta)
	testsDeltaStr := fmt.Sprintf("%+d", q.TestsDelta)

	fmt.Fprintf(sb, "| Metric | Before | After | Delta |\n")
	fmt.Fprintf(sb, "|--------|--------|-------|-------|\n")
	fmt.Fprintf(sb, "| Lint errors | %d | %d | %s |\n", q.LintErrorsBefore, q.LintErrorsAfter, lintDeltaStr)
	fmt.Fprintf(sb, "| Tests passing | %d | %d | %s |\n", q.TestsPassedBefore, q.TestsPassedAfter, testsDeltaStr)
	if q.CommitCount > 0 {
		fmt.Fprintf(sb, "| Commit count | — | — | %d |\n", q.CommitCount)
	}
	sb.WriteString("\n")
}

func writeReasoningSection(sb *strings.Builder, trace []string) {
	if len(trace) == 0 {
		return
	}

	fmt.Fprintf(sb, "## Reasoning Trace (top %d)\n\n", len(trace))
	for i, entry := range trace {
		fmt.Fprintf(sb, "%d. %s\n", i+1, strings.TrimSpace(entry))
	}
	sb.WriteString("\n")
}

// formatTokens formats token counts with comma separators.
func formatTokens(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	// Insert commas every 3 digits from the right.
	var result []byte
	for i, c := range s {
		pos := len(s) - i
		if pos%3 == 0 && i != 0 {
			result = append(result, ',')
		}
		result = append(result, byte(c))
	}
	return string(result)
}
