package intent

import (
	"strings"
	"testing"
	"time"

	"github.com/phuc-nt/dandori-cli/internal/db"
	"github.com/phuc-nt/dandori-cli/internal/quality"
)

// --- fixtures ---

func fixtureRun() *db.RunRecord {
	return &db.RunRecord{
		ID:            "a1b2c3d4-test-run",
		JiraIssueKey:  "CLITEST-42",
		AgentName:     "claude-code",
		Model:         "claude-sonnet-4",
		StartedAt:     time.Date(2026, 4, 30, 10, 14, 22, 0, time.UTC),
		DurationSec:   142,
		ExitCode:      0,
		Status:        "done",
		CostUSD:       0.3412,
		InputTokens:   10000,
		OutputTokens:  2500,
		GitHeadBefore: "a1b2c3d",
		GitHeadAfter:  "f4e5d6c",
	}
}

func fixtureIntentEvents() *db.RunIntentEvents {
	return &db.RunIntentEvents{
		Intent: &db.IntentData{
			FirstUserMsg: "Implement password hashing per CLITEST-42 spec",
			Summary:      "Switched from argon2 to bcrypt to align with existing deps.",
			SpecLinks: db.IntentSpecLinks{
				JiraKey:        "CLITEST-42",
				ConfluenceURLs: []string{"https://acme.atlassian.net/wiki/auth-spec"},
				SourcePaths:    []string{"README.md", "plans/plan.md"},
			},
		},
		Decisions: []db.IntentDecision{
			{
				Chosen:    "bcrypt",
				Rejected:  []string{"argon2"},
				Rationale: "existing dependencies already pull bcrypt",
			},
			{
				Chosen:   "SHA-256 for tokens",
				Rejected: []string{},
			},
		},
	}
}

func fixtureQuality() *quality.Metrics {
	return &quality.Metrics{
		RunID:             "a1b2c3d4-test-run",
		LintErrorsBefore:  5,
		LintErrorsAfter:   2,
		LintDelta:         -3,
		TestsPassedBefore: 80,
		TestsPassedAfter:  87,
		TestsDelta:        7,
		LinesAdded:        87,
		LinesRemoved:      12,
		FilesChanged:      4,
		CommitCount:       3,
	}
}

func fixtureTools() []db.ToolUsageSummary {
	return []db.ToolUsageSummary{
		{Tool: "Read", Count: 22},
		{Tool: "Edit", Count: 15},
		{Tool: "Bash", Count: 9},
	}
}

// --- BuildRunReport tests ---

func TestBuildRunReport_AllSections(t *testing.T) {
	data := &ReportData{
		Run:     fixtureRun(),
		Intent:  fixtureIntentEvents(),
		Quality: fixtureQuality(),
		Tools:   fixtureTools(),
	}
	out := BuildRunReport(data)

	mustContain(t, out, []string{
		"# Incident Report",
		"CLITEST-42",
		"claude-code",
		"2026-04-30T10:14:22Z",
		"done",
		"$0.3412",
		"## Intent",
		"Implement password hashing",
		"Switched from argon2 to bcrypt",
		"Jira: CLITEST-42",
		"Confluence",
		"auth-spec",
		"README.md",
		"## Key Decisions",
		"⚠️",
		"bcrypt",
		"argon2",
		"existing dependencies",
		"SHA-256 for tokens",
		"## Tool / Skill Usage",
		"Read",
		"22",
		"## Quality",
		"-3",
		"+7",
		"87",
		"12",
		"## Diff Stats",
		"a1b2c3d",
		"f4e5d6c",
		"Files changed: 4",
		"Generated by dandori incident-report",
	})
}

func TestBuildRunReport_NoIntentPlaceholder(t *testing.T) {
	data := &ReportData{
		Run:    fixtureRun(),
		Intent: &db.RunIntentEvents{}, // no intent.extracted, no decisions
	}
	out := BuildRunReport(data)

	mustContain(t, out, []string{
		"## Intent",
		"_no intent captured_",
		"## Key Decisions",
		"_no decisions captured_",
	})
}

func TestBuildRunReport_NoQualityPlaceholder(t *testing.T) {
	data := &ReportData{
		Run:     fixtureRun(),
		Intent:  &db.RunIntentEvents{},
		Quality: nil,
	}
	out := BuildRunReport(data)

	mustContain(t, out, []string{
		"## Quality",
		"_no quality metrics captured_",
		"## Diff Stats",
		// Git heads still present even without quality metrics
		"a1b2c3d",
	})
}

func TestBuildRunReport_NoDiffWhenNoGitAndNoMetrics(t *testing.T) {
	run := fixtureRun()
	run.GitHeadBefore = ""
	run.GitHeadAfter = ""

	data := &ReportData{
		Run:     run,
		Intent:  &db.RunIntentEvents{},
		Quality: nil,
	}
	out := BuildRunReport(data)

	mustContain(t, out, []string{"_no diff data captured_"})
}

func TestBuildRunReport_NoToolsPlaceholder(t *testing.T) {
	data := &ReportData{
		Run:    fixtureRun(),
		Intent: &db.RunIntentEvents{},
		Tools:  nil,
	}
	out := BuildRunReport(data)

	mustContain(t, out, []string{
		"## Tool / Skill Usage",
		"_no tool events captured_",
	})
}

func TestBuildRunReport_AdvisoryTag(t *testing.T) {
	data := &ReportData{
		Run:    fixtureRun(),
		Intent: fixtureIntentEvents(),
	}
	out := BuildRunReport(data)

	if !strings.Contains(out, "⚠️ Decisions extracted via heuristic") {
		t.Error("advisory tag missing from decisions section")
	}
}

func TestBuildRunReport_ReasoningTrace(t *testing.T) {
	data := &ReportData{
		Run:       fixtureRun(),
		Intent:    &db.RunIntentEvents{},
		Reasoning: []string{"Thinking about the spec...", "Starting with the model layer."},
	}
	out := BuildRunReport(data)

	mustContain(t, out, []string{
		"## Reasoning Trace",
		"Thinking about the spec",
		"Starting with the model layer",
	})
}

func TestBuildRunReport_ReasoningAbsent(t *testing.T) {
	data := &ReportData{
		Run:    fixtureRun(),
		Intent: &db.RunIntentEvents{},
	}
	out := BuildRunReport(data)

	if strings.Contains(out, "## Reasoning Trace") {
		t.Error("reasoning section should not appear when trace is empty")
	}
}

// --- BuildTaskReport tests ---

func TestBuildTaskReport_CrossRunSummary(t *testing.T) {
	run1 := fixtureRun()
	run2 := fixtureRun()
	run2.ID = "b2c3d4e5-second-run"
	run2.CostUSD = 0.1000
	run2.InputTokens = 5000
	run2.OutputTokens = 1000

	data := &TaskReportData{
		JiraKey: "CLITEST-42",
		Runs: []*ReportData{
			{Run: run1, Intent: fixtureIntentEvents(), Quality: fixtureQuality()},
			{Run: run2, Intent: &db.RunIntentEvents{}},
		},
	}
	out := BuildTaskReport(data)

	mustContain(t, out, []string{
		"# Incident Report — Task CLITEST-42",
		"## Cross-run Summary",
		"Total runs",
		"2",
		"Cumulative cost",
		"Iteration count",
		"## Run 1 of 2",
		"## Run 2 of 2",
		"Generated by dandori incident-report",
	})
}

func TestBuildTaskReport_SingleRun(t *testing.T) {
	data := &TaskReportData{
		JiraKey: "CLITEST-1",
		Runs: []*ReportData{
			{Run: fixtureRun(), Intent: &db.RunIntentEvents{}},
		},
	}
	out := BuildTaskReport(data)

	if !strings.Contains(out, "Total runs") {
		t.Error("cross-run summary missing")
	}
	if !strings.Contains(out, "## Run 1 of 1") {
		t.Error("run block header missing")
	}
}

// --- formatTokens ---

func TestFormatTokens(t *testing.T) {
	cases := []struct {
		n    int
		want string
	}{
		{0, "0"},
		{999, "999"},
		{1000, "1,000"},
		{12500, "12,500"},
		{1234567, "1,234,567"},
	}
	for _, c := range cases {
		got := formatTokens(c.n)
		if got != c.want {
			t.Errorf("formatTokens(%d) = %q, want %q", c.n, got, c.want)
		}
	}
}

// --- helpers ---

func mustContain(t *testing.T, haystack string, needles []string) {
	t.Helper()
	for _, needle := range needles {
		if !strings.Contains(haystack, needle) {
			t.Errorf("report missing %q\n\n--- report ---\n%s", needle, haystack)
		}
	}
}
